### ISSUE TITLE
Error: could not find a ready tiller pod 的解决方案: tiller的版本跟新，helm没跟上

### ISSUE THREAD

**Issue by rushairer** [maguowei/k8s-docker-desktop-for-mac#11]
Error: could not find a ready tiller pod

原因是作者更新了 tiller到 2.14.1
helm init的时候，还是去找 2.14.0

```
Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.14.0": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

需要手工修改 tiller-deploy 里面的  "image": "gcr.io/kubernetes-helm/tiller:v2.14.0" 成  "image": "gcr.io/kubernetes-helm/tiller:v2.14.1" 就可以使用了

**Comment by maguowei** [comment]
brew 安装的helm 已经更新到  2.14.1 了，你 `brew upgrade` 试一下。

> brew info kubernetes-helm
kubernetes-helm: stable 2.14.1 (bottled), HEAD
The Kubernetes package manager
https://helm.sh/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubernetes-helm.rb
==> Dependencies
Build: glide ✘, go ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 28,963 (30 days), 75,692 (90 days), 247,473 (365 days)
install_on_request: 28,387 (30 days), 74,310 (90 days), 243,159 (365 days)
build_error: 0 (30 days)

https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubernetes-helm.rb#L5

**Comment by rushairer** [comment]
多谢
