### ISSUE TITLE
Unable to connect to the server: x509: certificate is valid for docker-for-desktop

### ISSUE THREAD

**Issue by Xarrow** [maguowei/k8s-docker-desktop-for-mac#15]
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: x509: certificate is valid for docker-for-desktop, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, host.docker.internal, not kubernetes.docker.internal

**Comment by Xarrow** [comment]
has solved

**Comment by saket88** [comment]
how to solve this issue

**Comment by SunYingJiee** [comment]
how？

**Comment by nicholasericksen** [comment]
For anyone looking at this now...you might try this

create a backup of the `.kube` config file (note that you need to replace `<username>` with you username on mac)

```
cp /Users/<username>/.kube/config .
```

Then remove it
```
rm /Users/<username>/.kube/config
```

and restart the docker desktop for mac kubernetes cluster in the app.  It worked for me
