### ISSUE TITLE
上周自动升级后，就一直"Kubernetes is starting"

### ISSUE THREAD

**Issue by vzzy** [maguowei/k8s-docker-desktop-for-mac#16]
上周自动升级后，就一直"Kubernetes is starting"。 应该都是最新版。  
帮忙分析下啥原因？ 谢谢。

Mac OS   Mojave 10.14.6
Version 2.1.2.0(38030)
Channel  edge
Engine 19.03.2
Kubernetes v1.14.6

错误日志：  
`2019-09-16 15:12:07.881411+0800  localhost com.docker.driver.amd64-linux[6156]: (libsystem_info.dylib) [com.apple.network.libinfo:getaddrinfo] nat64_v4_requires_synthesis(127.0.0.1) == false
2019-09-16 15:12:07.883410+0800  localhost com.docker.driver.amd64-linux[6156]: Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF`

**Comment by maguowei** [comment]
@vzzy 已经更新，请再试一下，之前由于疏忽只同步了镜像到docker hub，没有将镜像列表更新. 目前已经个更新支持到最新版本

**Comment by vzzy** [comment]
确认已正常。 感谢。
