### ISSUE TITLE
要更新了，新版本又不行了。。。

### ISSUE THREAD

**Issue by FrankYan2013** [maguowei/k8s-docker-desktop-for-mac#17]

**Comment by madre** [comment]
貌似新版本用的是 k8s的 1.14.6，这里用的是 1.14.3。
匹配不上，所以更新不了。
测试下，目前只能使用 2.1.1.0，这个是兼容的…

**Comment by maguowei** [comment]
> 貌似新版本用的是 k8s的 1.14.6，这里用的是 1.14.3。
> 匹配不上，所以更新不了。
> 测试下，目前只能使用 2.1.1.0，这个是兼容的…

已经更新了镜像列表，之前是疏忽遗漏了更新。目前已经更新到最近版本 @FrankYan2013 @madre
