### ISSUE TITLE
增加stable版本支持

### ISSUE THREAD

**Issue by maguowei** [maguowei/k8s-docker-desktop-for-mac#24]
当前只同步了最新的 edge 版本对应的kubernetes 依赖镜像，须增加stable版本的支持

**Comment by mzeht** [comment]
最新稳定版 k8s起不来 一直starting，images信息更新下哦

**Comment by IT-zhengang** [comment]
v1.21.2 k8s镜像有最新的嘛，求更新

**Comment by maguowei** [comment]
docker desktop 已不再去分 edge 与stable 版本

**Comment by maguowei** [comment]
upgrade version 3.5.1 with kubernetes: v1.21.2 https://github.com/maguowei/k8s-docker-desktop-for-mac/commit/beab51c04855628bb836493e4744473d07a288d1

**Comment by IT-zhengang** [comment]
kubelet  Failed to pull image "k8s.gcr.io/coredns/coredns:v1.8.0": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

image tag is error ,please check once;

fix: 
> cat images                                                                                                  
k8s.gcr.io/kube-proxy:v1.21.2=gotok8s/kube-proxy:v1.21.2
k8s.gcr.io/kube-controller-manager:v1.21.2=gotok8s/kube-controller-manager:v1.21.2
k8s.gcr.io/kube-scheduler:v1.21.2=gotok8s/kube-scheduler:v1.21.2
k8s.gcr.io/kube-apiserver:v1.21.2=gotok8s/kube-apiserver:v1.21.2
**k8s.gcr.io/coredns/coredns:v1.8.0=gotok8s/coredns:v1.8.0**
k8s.gcr.io/pause:3.4.1=gotok8s/pause:3.4.1
k8s.gcr.io/etcd:3.4.13-0=gotok8s/etcd:3.4.13-0
