### ISSUE TITLE
第二步执行完毕后，第三步一直卡在starting

### ISSUE THREAD

**Issue by zxcstc1256** [maguowei/k8s-docker-desktop-for-mac#37]
系统版本 macOS Catalina 10.15.7
Docker Desktop版本 Channel:edge Version:2.4.2.0(48975)

![image](https://user-images.githubusercontent.com/4626239/97082563-3f8db600-163d-11eb-8971-563e1252fc81.png)

这是第二步的执行结果
`➜  k8s-docker-for-mac git:(master) ./load_images.sh
images found.
v1.19.2: Pulling from gotok8s/kube-proxy
Digest: sha256:a5e646dc3b90ff921bcabd25f42af79b0524402485ebb3a81a15d65cd858d1ed
Status: Downloaded newer image for gotok8s/kube-proxy:v1.19.2
docker.io/gotok8s/kube-proxy:v1.19.2
Untagged: gotok8s/kube-proxy:v1.19.2
Untagged: gotok8s/kube-proxy@sha256:a5e646dc3b90ff921bcabd25f42af79b0524402485ebb3a81a15d65cd858d1ed
v1.19.2: Pulling from gotok8s/kube-controller-manager
Digest: sha256:f8c271e12218a32eecd39ffe98f9e47dae6554fc0ca30071bf32280da00b02dd
Status: Downloaded newer image for gotok8s/kube-controller-manager:v1.19.2
docker.io/gotok8s/kube-controller-manager:v1.19.2
Untagged: gotok8s/kube-controller-manager:v1.19.2
Untagged: gotok8s/kube-controller-manager@sha256:f8c271e12218a32eecd39ffe98f9e47dae6554fc0ca30071bf32280da00b02dd
v1.19.2: Pulling from gotok8s/kube-scheduler
Digest: sha256:67076f919fd65602ba69219d2a630737cd826459d866d85f106b36f4857505d0
Status: Downloaded newer image for gotok8s/kube-scheduler:v1.19.2
docker.io/gotok8s/kube-scheduler:v1.19.2
Untagged: gotok8s/kube-scheduler:v1.19.2
Untagged: gotok8s/kube-scheduler@sha256:67076f919fd65602ba69219d2a630737cd826459d866d85f106b36f4857505d0
v1.19.2: Pulling from gotok8s/kube-apiserver
Digest: sha256:b119baef2a60b537c264c0ea009f63095169af089e1a36fb4167693f1b60cd1e
Status: Downloaded newer image for gotok8s/kube-apiserver:v1.19.2
docker.io/gotok8s/kube-apiserver:v1.19.2
Untagged: gotok8s/kube-apiserver:v1.19.2
Untagged: gotok8s/kube-apiserver@sha256:b119baef2a60b537c264c0ea009f63095169af089e1a36fb4167693f1b60cd1e
1.6.7: Pulling from gotok8s/coredns
Digest: sha256:695a5e109604331f843d2c435f488bf3f239a88aec49112d452c1cbf87e88405
Status: Downloaded newer image for gotok8s/coredns:1.6.7
docker.io/gotok8s/coredns:1.6.7
Untagged: gotok8s/coredns:1.6.7
Untagged: gotok8s/coredns@sha256:695a5e109604331f843d2c435f488bf3f239a88aec49112d452c1cbf87e88405
3.2: Pulling from gotok8s/pause
Digest: sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
Status: Downloaded newer image for gotok8s/pause:3.2
docker.io/gotok8s/pause:3.2
Untagged: gotok8s/pause:3.2
Untagged: gotok8s/pause@sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
3.4.3-0: Pulling from gotok8s/etcd
Digest: sha256:4198ba6f82f642dfd18ecf840ee37afb9df4b596f06eef20e44d0aec4ea27216
Status: Downloaded newer image for gotok8s/etcd:3.4.3-0
docker.io/gotok8s/etcd:3.4.3-0
Untagged: gotok8s/etcd:3.4.3-0
Untagged: gotok8s/etcd@sha256:4198ba6f82f642dfd18ecf840ee37afb9df4b596f06eef20e44d0aec4ea27216 `

**Comment by tanpenggood** [comment]
+1  k8s is starting

执行 `load_images.sh`成功，无异常。

重启啥的都是starting，在线求助 🙏🙏🙏

- macOS Catalina 10.15.7
- docker desktop 2.4.0.0(48506)
- docker engine 19.03.13
- docker compose 1.27.4
- k8s v1.18.8

**Comment by everbef0re** [comment]
我遇到了一样的问题，我那个enable kubernetes勾勾甚至取消不了。我重装了，然后先直接配置了proxy，再enable kubernetes启动成功了。没跑这个仓库的脚本

**Comment by c2498168786** [comment]
> 我遇到了一样的问题，我那个enable kubernetes勾勾甚至取消不了。我重装了，然后先直接配置了proxy，再enable kubernetes启动成功了。没跑这个仓库的脚本

哪个proxy链接可以分享一下吗
{
  "experimental": false,
  "features": {
    "buildkit": true
  },
  "registry-mirrors": [
    "https://k8wxws52.mirror.aliyuncs.com"
  ]
}我这个没用

**Comment by lwmxiaobei** [comment]
按照步骤执行了，没啥用

**Comment by wsx812585705** [comment]
成功了
macOS Big Sur 11.1 最新版本
docker-desktop 3.0.1
docker engine 20.10.0
docker compose 1.27.4
kubernetes: v1.19.3
执行脚本时，修改images文件中镜像tag
k8s.gcr.io/kube-proxy:v1.19.3=gotok8s/kube-proxy:v1.19.3
k8s.gcr.io/kube-controller-manager:v1.19.3=gotok8s/kube-controller-manager:v1.19.3
k8s.gcr.io/kube-scheduler:v1.19.3=gotok8s/kube-scheduler:v1.19.3
k8s.gcr.io/kube-apiserver:v1.19.3=gotok8s/kube-apiserver:v1.19.3
k8s.gcr.io/coredns:1.7.0=gotok8s/coredns:1.7.0
k8s.gcr.io/pause:3.2=gotok8s/pause:3.2
k8s.gcr.io/etcd:3.4.13-0=gotok8s/etcd:3.4.13-0
应该是每个版本的k8s, 每个组件的版本必须按官方的一致。上面是v1.19.3的镜像版本

**Comment by zoopnin** [comment]
@wsx812585705 我还是没成功~  我和你的系统以及版本是一致的。

**Comment by wsx812585705** [comment]
> @wsx812585705 我还是没成功~ 我和你的系统以及版本是一致的。

是镜像没拉下来吗？

**Comment by shengdoushi** [comment]
> 成功了
> macOS Big Sur 11.1 最新版本
> docker-desktop 3.0.1
> docker engine 20.10.0
> docker compose 1.27.4
> kubernetes: v1.19.3
> 执行脚本时，修改images文件中镜像tag
> k8s.gcr.io/kube-proxy:v1.19.3=gotok8s/kube-proxy:v1.19.3
> k8s.gcr.io/kube-controller-manager:v1.19.3=gotok8s/kube-controller-manager:v1.19.3
> k8s.gcr.io/kube-scheduler:v1.19.3=gotok8s/kube-scheduler:v1.19.3
> k8s.gcr.io/kube-apiserver:v1.19.3=gotok8s/kube-apiserver:v1.19.3
> k8s.gcr.io/coredns:1.7.0=gotok8s/coredns:1.7.0
> k8s.gcr.io/pause:3.2=gotok8s/pause:3.2
> k8s.gcr.io/etcd:3.4.13-0=gotok8s/etcd:3.4.13-0
> 应该是每个版本的k8s, 每个组件的版本必须按官方的一致。上面是v1.19.3的镜像版本

我的改下这个可以了

**Comment by jnan88** [comment]
docker-desktop 3.0.4 : https://www.yuque.com/jnliok/pub/xdb0vg

**Comment by t880216t** [comment]
成功了，修改了images，最后一个镜像的版本 `3.4.3 >  3.4.13`。
`k8s.gcr.io/etcd:3.4.13-0=gotok8s/etcd:3.4.13-0`

**Comment by drafish** [comment]
我改了images，自己笔记本系统是11.1的，没成功；公司电脑是10.15的，成功了。

**Comment by maguowei** [comment]
#43 #42

**Comment by BinZhiZhu** [comment]
我是刚刚拉的repo，然后执行了:
```bash
./load_images.sh
```

然后重启了docker以及尝试reset 集群 好像还是有问题，一直卡住
