### ISSUE TITLE
k8s-docker-desktop-for-mac/images中etcd版本错误

### ISSUE THREAD

**Issue by zkfopen** [maguowei/k8s-docker-desktop-for-mac#42]
![image](https://user-images.githubusercontent.com/29174476/107494965-69f28780-6bca-11eb-89f7-781b92a0cd81.png)
原来的
`k8s.gcr.io/etcd:3.4.3-0=gotok8s/etcd:3.4.13-0`
正确的
`k8s.gcr.io/etcd:3.4.13-0=gotok8s/etcd:3.4.13-0`

**Comment by pengbotao** [comment]
估计打漏了，重新打下tag就正常了
