### ISSUE TITLE
docker for mac kubernetes v1.21.2 启动失败

### ISSUE THREAD

**Issue by ngyhd** [maguowei/k8s-docker-desktop-for-mac#46]
MacOS Catalina 10.15.7
docker-desktop 3.5.2.18
docker engine v20.10.7
kubernetes: v1.21.2
![截屏2021-07-21 下午10 57 42](https://user-images.githubusercontent.com/29095207/126511473-4adf238c-3a6b-4005-9501-222ca46f0a2e.png)
![截屏2021-07-21 下午10 57 56](https://user-images.githubusercontent.com/29095207/126511522-0a8fd91e-a930-455a-b1b2-e7717667b1f2.png)

images和kubernetes版本一致，不知道为什么启动失败，不知该如何解决？

**Comment by ngyhd** [comment]
mac uninstall docker
重新安装docker可以

**Comment by BinZhiZhu** [comment]
> mac uninstall docker
> 重新安装docker可以

老哥，卸载重装又可以？？？我的一直卡starting

**Comment by ngyhd** [comment]
> > mac uninstall docker
> > 重新安装docker可以
> 
> 老哥，卸载重装又可以？？？我的一直卡starting

卸载，安装，启动脚本拉取镜像，启动k8s
