### ISSUE TITLE
k8s镜像都已经下载了，而且正常启动了，但是docker显示的那个状态没有任何变化

### ISSUE THREAD

**Issue by Oldmoooon** [maguowei/k8s-docker-desktop-for-mac#7]
现象如图：

![image](https://user-images.githubusercontent.com/13718160/50435585-d5ab0500-091c-11e9-979f-225b76274b73.png)

![image](https://user-images.githubusercontent.com/13718160/50435603-e65b7b00-091c-11e9-95ab-93ddbfb6895f.png)

**Comment by CGJzzz** [comment]
我显示是docker i
s running ,kubenetes is unknown state

**Comment by hscspring** [comment]
https://github.com/AliyunContainerService/k8s-for-docker-desktop/tree/v2.0.0.2

v2.0.0.2 分支

**Comment by magicdvd** [comment]
![WeChat11d69e6dd90ba9e7902ff474494ba06f](https://user-images.githubusercontent.com/1028774/58624659-5d999e80-8303-11e9-87d2-f3f58b08ac98.png)

![WeChatc89fce256596679af630eea0929a6081](https://user-images.githubusercontent.com/1028774/58624698-73a75f00-8303-11e9-9c8e-0065a31d6cc8.png)

我的情况，是否有解决方案？

**Comment by XljBear** [comment]
> ![WeChat11d69e6dd90ba9e7902ff474494ba06f](https://user-images.githubusercontent.com/1028774/58624659-5d999e80-8303-11e9-87d2-f3f58b08ac98.png)
> 
> ![WeChatc89fce256596679af630eea0929a6081](https://user-images.githubusercontent.com/1028774/58624698-73a75f00-8303-11e9-9c8e-0065a31d6cc8.png)
> 
> 我的情况，是否有解决方案？

遇到了一模一样的情况

**Comment by Oldmoooon** [comment]
我的问题在docker的某次更新后已经解决，所以现在关闭这个issue。

**Comment by kid1412621** [comment]
> > ![WeChat11d69e6dd90ba9e7902ff474494ba06f](https://user-images.githubusercontent.com/1028774/58624659-5d999e80-8303-11e9-87d2-f3f58b08ac98.png)
> > ![WeChatc89fce256596679af630eea0929a6081](https://user-images.githubusercontent.com/1028774/58624698-73a75f00-8303-11e9-9c8e-0065a31d6cc8.png)
> > 我的情况，是否有解决方案？
> 
> 遇到了一模一样的情况

+1, 最新版 docker 貌似失效了
