### ISSUE TITLE
kubectl cluster-info 命令

### ISSUE THREAD

**Issue by wenlin1** [maguowei/k8s-docker-desktop-for-mac#9]
docker 和 Kubernetes都启动了 用kubectl cluster-info 命令查看显示：
from server (InternalError): an error on the server ("") has prevented the request from succeeding (get nodes)

请问一下这个是什么原因导致的？

**Comment by maguowei** [comment]
请升级到最新的版本试一下。 如果还有问题看一下是不是开了全局代理？
